### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [ChernyshenkoTaras/CustomCamera#1]
Hi @ChernyshenkoTaras  would you like me to design also a logo for this project of yours? 
-Tobaloidee

**Comment by ChernyshenkoTaras** [comment]
Hi,
yes, sure. I will appreciate your help!

**Comment by Tobaloidee** [comment]
okay, will show it here when done :+1:

**Comment by Tobaloidee** [comment]
here is my design for this project @ChernyshenkoTaras  pls let me know what you have in mind

Design concept: 
- letters "TC" was incorporated with the camera shape/symbol to form a unique look. Simple and minimal and visible even in small scales.

![pres-01](https://user-images.githubusercontent.com/36028424/43587602-26fb01fa-969d-11e8-8c14-51ecdbf606f0.png)

**Comment by ChernyshenkoTaras** [comment]
It's look so good. I really like your designs. Please add it to readme and submit pull request. Thanks!

**Comment by Tobaloidee** [comment]
thanks! i will finalize the files again and make a PR..👍

**Comment by Tobaloidee** [comment]
here's the PR #2 and you can get all the SVG-PNG-Ai formats & versions on this [LINK](https://drive.google.com/drive/u/0/folders/1q26W-vJZunXgA62Nv9jYPK8aJCiIBGce)

Thanks so much! I will check also the other projects and see if i can give a logo idea again. :) 

-Tobaloidee

**Comment by ChernyshenkoTaras** [comment]
Thank you so much!
